sever:
  port: 8083
  servlet:
    context:
      path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblogapp?useSSL=false
    username: root
    password: dbwnqhd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect:
        hibernate: org.hibernate.dialect.MySQL8Dialect

